USE LLIBREIRA;

DELIMITER //

DROP PROCEDURE IF EXISTS sp01_Libres_Aprop_Estoc//

CREATE PROCEDURE sp01_Libres_Aprop_Estoc()
BEGIN
SELECT  TITOL,EDITORAL,ESTOC
FROM LLIBRES
WHERE ESTOC <=5;
END //
DELIMITER ;